# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.8'

services:
  sqlserver:
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server
    ports: 
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=yourStrongPassword12#
    volumes: 
      - sqldata:/var/opt/mssql
    deploy:
      resources:
          reservations:
              cpus: '2'
              memory: 2GB
  web-app:
    container_name: web-app
    # build:
    #   dockerfile: ./Dockerfile
    #image: softunibazar
    image: bozhidarivanovbazarscr.azurecr.io/softunibazar
    domainname: bozhidarivanov
    ports: 
        - "80:80"
    restart: on-failure

volumes:
    sqldata:
      #external: false
      driver: azure_file
      driver_opts:
          share_name: sql-volumes
          storage_account_name: bozhidarivanovbazarsa